# -*- coding: utf-8 -*-
"""hw3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3xUuhX-TcBcuYQkmfY_SlYTTPGADL-C
"""

#Büşra Gülnihan Daşcıoğlu

Ogr1 = input("1. Öğrencinin adini giriniz:")
Ogr1Not =()

print("1. Öğrencinin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

Ogr1Not=(result)
print(Ogr1,":" ,Ogr1Not)

notlar = list()
midterm = input("Midterm Point:")
notlar.append(midterm)
print ("Midterm Note:" , notlar)

Ogr2 = input("2. Öğrencinin Adini Giriniz:")
Ogr2Not = ()
print("2. Öğrenci'nin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

Ogr2Not=(result)
print(Ogr2,":" ,Ogr2Not)

Ogr3 = input("3. Öğrencinin adini giriniz:")
Ogr3Not =()
print("3. Öğrencinin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

Ogr3Not=(result)
print(Ogr3,":" ,Ogr3Not)

Ogr4 = input("4. Öğrencinin Adini Giriniz:")
Ogr4Not = ()
print("4. Öğrenci'nin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

Ogr4Not=(result)
print(Ogr4,":" ,Ogr4Not)

Ogr5 = input("5. Öğrencinin Adini Giriniz:")
Ogr5Not = ()
print("5. Öğrenci'nin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

Ogr5Not=(result)
print(Ogr5,":" ,Ogr5Not)

Ogrenci = {Ogr1 : Ogr1Not, Ogr2 : Ogr2Not, Ogr3 : Ogr3Not, Ogr4 : Ogr4Not, Ogr5 : Ogr5Not}
print (Ogrenci)
type (Ogrenci)

def sırala(liste):
    return liste[1]

GANO = [('Öğr1', Ogr1Not),
        ('Öğr2', Ogr2Not),
        ('Öğr3', Ogr3Not),
        ('Öğr4', Ogr4Not),
        ('Öğr5', Ogr5Not),]

print(*sorted(GANO, key=sırala), sep='\n')

