# -*- coding: utf-8 -*-
"""final project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SBiB8bqH5shX7Ggsmlbuywwdl_PZ0NoN
"""

#Büşra Gülnihan Daşcıoğlu Final Projesi
class Question:
     def __init__(self, prompt, answer):
          self.prompt = prompt
          self.answer = answer

print ("Bilgi yarışmamıza hoşgeldiniz!")
question_prompts = [
     "\n1-Magna Carta hangi ülke ile yapılmıştır?\n(a)İngiltere\n(b)İspanya\n(c)İtalya \nanswer: ",
     "\n2-Galatasaray hangi yıl UEFA kupasını kaldırmıştır?\n(a)2000\n(b)2003\n(c)2001 \nanswer:",
     "\n3-Fransız İhtilali hangi yıllar arasında gerçekleşmiştir? \n(a)1768-1787\n(b)1789-1799\n(c)1776-1789 \nanswer: ",
     "\n4-Süper Lig'de hangi takımın 4 yıldızı vardır?'\n(a)Fenerbahçe\n(b)Beşiktaş\n(c)Galatasaray\nanswer:",
     "\n5-Kuvvet birimi nedir?'\n(a)Joule\n(b)Newton\n(c)Pascal \nanswer: ",
     "\n6-Kuyucaklı Yusuf hangi yazarımıza aittir? \n(a)Sabahattin Ali\n(b)Yaşar Kemal\n(c)Orhan Kemal\nanswer:",
     "\n7-Elektrik devresinde direnç hangi harfle gösterilir?\n(a)R\n(b)A\n(c)D\nanswer:",
     "\n8-Fas'ın başkenti hangi şehirdir?\n(a)Kazablanka\n(b)Kahire\n(c)Rabat\nanswer:",
     "\n9-1 metre kaç milimetredir?\n(a)10\n(b)1000\n(c)100000\nanswer:",
     "\n10-Hangi şairimiz ikinci yeni akımına dahildir? \n(a)Sezai Karakoç\n(b)Can Yücel\n(c)Orhan Veli\nanswer:",
]

questions = [
     Question(question_prompts[0], "a"),
     Question(question_prompts[1], "a"),
     Question(question_prompts[2], "b"),
     Question(question_prompts[3], "c"),
     Question(question_prompts[4], "b"),
     Question(question_prompts[5], "a"),
     Question(question_prompts[6], "a"),
     Question(question_prompts[7], "c"),
     Question(question_prompts[8], "b"),
     Question(question_prompts[9], "a"),
]

def run_quiz(questions):
     score = 0
     for question in questions:
          answer = input(question.prompt)
          if answer == question.answer:
               score += 10
     if score <= 50:
        print("Malesef başarısız oldunuz.")
     else:
       print("Tebrikler!")


run_quiz(questions)