# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Wu_fIt207l-aFC9CNlMvvtF2Fj4pa7r
"""

#busragdascioglu@gmail.com Büşra Gülnihan Daşcıoğlu

CV1 = {"ad": "Ahmet", "soyad": "Işık", "Meslek": "Mühendis", "Başvurulan Pozisyon": "Yazılım Mühendisliği", "Mezuniyet Tarihi": "2016", "Doğum Tarihi": "03.05.1990"}
CV2 = {"ad": "Ali", "soyad": "Öztürk", "Meslek": "Öğretmen", "Başvurulan Pozisyon": "Matematik Öğretmeni", "Mezuniyet Tarihi": "2012", "Doğum Tarihi": "01.02.1983"}
CV3 = {"ad": "Büşra", "soyad": "Yıldız", "Meslek": "Mühendis", "Başvurulan Pozisyon": "Endüstri Mühendisliği", "Mezuniyet Tarihi": "2014", "Doğum Tarihi": "07.04.1993"}
CV4 = {"ad": "Melis", "soyad": "Küçük", "Meslek": "PDR", "Başvurulan Pozisyon": "Psikolog", "Mezuniyet Tarihi": "2015", "Doğum Tarihi": "16.08.1991"}
CV5 = {"ad": "Melek", "soyad": "Ersöz", "Meslek": "Tıp", "Başvurulan Pozisyon": "Doktor", "Mezuniyet Tarihi": "2018", "Doğum Tarihi": "11.03.1996"}

type(CV1)
type(CV2)
type(CV3)
type(CV4)
type(CV5)

print(CV1)
print(CV2)
print(CV3)
print(CV4)
print(CV5)